version: '3'

services:
  proxy:
    image: staticfloat/nginx-certbot
    container_name: dice-map-proxy
    ports:
      - 80:80/tcp
      - 443:443/tcp
    volumes:
      - ./proxy/proxy.conf:/etc/nginx/user.conf:ro
      - letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: ${CERTBOT_EMAIL}
      DOMAIN: ${DOMAIN}
      WEB_PORT: ${WEB_PORT}
      API_PORT: ${API_PORT}
      SOCKET_PORT: ${SOCKET_PORT}
      ENVSUBST_VARS: DOMAIN WEB_PORT API_PORT SOCKET_PORT
    restart: "unless-stopped"
  client:
    build:
      context: ./client
      dockerfile: client-production.dockerfile
    container_name: dice-map-client
    volumes:
      - /client/node_modules
    restart: "unless-stopped"
  api:
    build:
      context: ./api
      dockerfile: api-production.dockerfile
      args:
        - API_PORT=${API_PORT}
        - SOCKET_PORT=${SOCKET_PORT}
    container_name: dice-map-api
    volumes:
      - /api/node_modules
    depends_on:
      - db
    restart: "unless-stopped"
  db:
    image: mongo:4.4.2
    container_name: dice-map-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    expose:
      - "${MONGO_PORT}"
    volumes:
      - ./data/db:/data/db
    restart: always

volumes:
  letsencrypt: