version: '3'

services:
  client:
    build:
      context: ./client
    container_name: dice-map-client-dev
    ports:
      - "4200:4200"
    volumes:
      - ./client:/client
      - ./client/node_modules:/client/node_modules
    restart: "unless-stopped"
    tty: true
  api:
    build:
      context: ./api
    container_name: dice-map-api-dev
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./api:/api
      - ./api/node_modules:/api/node_modules
    restart: "unless-stopped"
    depends_on:
      - db
  db:
    image: mongo
    container_name: dice-map-db-dev
    ports:
      - "27017:27017"