name: DEPLOY
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: SET HOST
        run: sed -i 's/HOST/'"$HOST"'/g' ./client/src/environments/environment.prod.ts
        env:
          HOST: ${{ secrets.HOST }}

      - name: Run build
        run: |
          cd client
          npm install
          npm run build -- --output-path=./dist/out --prod
      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY }}
          source: "client/dist/out/"
          target: "app/dice-game/"

      - name: 'deploy'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd app/dice-game
            git checkout main
            git fetch --all
            git reset --hard origin/main
            docker image prune -a -f
            sh docker-prod.sh restart
